# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: db56257b3f9cb1a5e38e5f1ce5ebd50b47fea5ada81cd8f7f2a353b5be2e4b57162eea0961222f70d7fe1ecae3c8042627868497ac75727f6679383b08350812

test:
  secret_key_base: 3c175cb6a2d0fe6288b42e8b396b0d8b66b37ab87fc6197a611852dc6cd31116006466a0d719db3df674a8e35fe90baeb403dced02c6dfb9078e9fc57cf782d0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
